name: Heroku CI

on:
  push:
    branches: [prod]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Heroku Action
      # You may pin to the exact commit or the version.
      # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
      uses: CDNievas/heroku-action@v1.0
      with:
        # Used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.HEROKU_APIKEY }}
        # Email from Heroku Account
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        # The appname to use for deploying/updating
        heroku_app_name: 'astralbot-prod'
        # Contents of the Procfile to save and deploy
        procfile: 'Procfile'
        # Path to an localized env file
        env_file: '.env'
