name: Heroku CI

on:
  push:
    branches: [prod]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_APIKEY}}
        heroku_app_name: "astralbot-prod" #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}
