name: Lint

on:
  pull_request:
  push:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm i
    - run: npm run prelint
    - run: npm run lint
